server:
  port: 8080

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: password

logging:
  level:
    com.lzb : debug

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    #配置mapper文件地址
  type-aliases-package: com.lzb.pojo    #配置别名
  configuration:
    map-underscore-to-camel-case: true
